export const TOGGLE_THEME = 'TOGGLE_THEME';

export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAIL = 'FETCH_COUNTRIES_FAIL';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const FETCH_FILTERED_COUNTRIES_START = 'FETCH_FILTERED_COUNTRIES_START';
export const FETCH_FILTERED_COUNTRIES_SUCCESS =
  'FETCH_FILTERED_COUNTRIES_SUCCESS';

export const FETCH_FILTERED_REGION_START = 'FETCH_FILTERED_REGION_START';
export const FETCH_FILTERED_REGION_SUCCESS = 'FETCH_FILTERED_REGION_SUCCESS';

export const PREV_PAGE = 'PREV_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';

export const INIT_ROUTES = 'INIT_ROUTES';

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAIL = 'FETCH_COUNTRY_FAIL';
